export const GOOGLE_DARK_THEME = {
  name: "Google-Dark",
  codeFontFamily: "0xProto",
  colors: {
    focusBorder: "#5876deff",
    foreground: "#e1dfdfff",
    "icon.foreground": "#e1dfdfff",
    "widget.shadow": "#0a0a0a4d",
    descriptionForeground: "#999999ff",
    errorForeground: "#f76769ff",
    "toolbar.hoverBackground": "#e1dfdf1f",
    "toolbar.activeBackground": "#e1dfdf3d",
    "textLink.foreground": "#88a3ffff",
    "textLink.activeForeground": "#98b1ffff",
    "textBlockQuote.background": "#292929ff",
    "textBlockQuote.border": "#535353ff",
    "textCodeBlock.background": "#3e3e3eff",
    "textPreformat.foreground": "#b0afafff",
    "textSeparator.foreground": "#6a6a6aff",
    "list.warningForeground": "#ffb256ff",
    "list.errorForeground": "#fa7b7cff",
    "button.background": "#7895ffff",
    "button.hoverBackground": "#88a3ffff",
    "button.foreground": "#000000ff",
    "button.secondaryBackground": "#535353ff",
    "button.secondaryForeground": "#ffffffff",
    "button.secondaryHoverBackground": "#6a6a6aff",
    "checkbox.background": "#292929ff",
    "checkbox.foreground": "#e1dfdfff",
    "checkbox.border": "#494949ff",
    "dropdown.background": "#292929ff",
    "dropdown.border": "#494949ff",
    "dropdown.foreground": "#e1dfdfff",
    "dropdown.listBackground": "#151515ff",
    "input.background": "#292929ff",
    "input.border": "#494949ff",
    "input.foreground": "#e1dfdfff",
    "input.placeholderForeground": "#999999ff",
    "inputValidation.errorBorder": "#f76769ff",
    "inputOption.activeBorder": "#5876deff",
    "inputOption.activeBackground": "#4563ca80",
    "inputOption.activeForeground": "#faf8f8ff",
    "badge.foreground": "#bbceffff",
    "badge.background": "#3252b8ff",
    "progressBar.background": "#5876deff",
    "titleBar.activeForeground": "#e1dfdfff",
    "titleBar.activeBackground": "#1f1f1fff",
    "titleBar.inactiveForeground": "#828282ff",
    "titleBar.inactiveBackground": "#151515ff",
    "titleBar.border": "#3e3e3eff",
    "commandCenter.background": "#1f1f1fff",
    "commandCenter.foreground": "#999999ff",
    "commandCenter.border": "#3e3e3eff",
    "commandCenter.activeBackground": "#292929ff",
    "commandCenter.activeForeground": "#e1dfdfff",
    "commandCenter.activeBorder": "#494949ff",
    "commandCenter.inactiveForeground": "#828282ff",
    "commandCenter.inactiveBorder": "#3e3e3eff",
    "activityBar.foreground": "#e1dfdfff",
    "activityBar.inactiveForeground": "#828282ff",
    "activityBar.background": "#1f1f1fff",
    "activityBarBadge.foreground": "#000000ff",
    "activityBarBadge.background": "#7895ffff",
    "activityBar.activeBorder": "#7895ffff",
    "activityBar.border": "#3e3e3eff",
    "sideBar.foreground": "#e1dfdfff",
    "sideBar.background": "#151515ff",
    "sideBar.border": "#3e3e3eff",
    "sideBarTitle.foreground": "#e1dfdfff",
    "sideBarSectionHeader.foreground": "#e1dfdfff",
    "sideBarSectionHeader.background": "#151515ff",
    "sideBarSectionHeader.border": "#3e3e3eff",
    "list.hoverForeground": "#e1dfdfff",
    "list.inactiveSelectionForeground": "#e1dfdfff",
    "list.activeSelectionForeground": "#e1dfdfff",
    "list.inactiveSelectionBackground": "#292929ff",
    "list.hoverBackground": "#292929ff",
    "list.activeSelectionBackground": "#343434ff",
    "list.inactiveFocusBackground": "#00258399",
    "list.focusBackground": "#002583ff",
    "tree.indentGuidesStroke": "#3e3e3eff",
    "notificationCenterHeader.foreground": "#828282ff",
    "notificationCenterHeader.background": "#292929ff",
    "notifications.foreground": "#e1dfdfff",
    "notifications.background": "#2e2e2eff",
    "notifications.border": "#494949ff",
    "notificationToast.border": "#494949ff",
    "notificationsErrorIcon.foreground": "#f76769ff",
    "notificationsWarningIcon.foreground": "#ffa23eff",
    "notificationsInfoIcon.foreground": "#999999ff",
    "pickerGroup.border": "#535353ff",
    "pickerGroup.foreground": "#e1dfdfff",
    "quickInput.background": "#151515ff",
    "quickInput.foreground": "#e1dfdfff",
    "quickInputTitle.background": "#151515ff",
    "keybindingLabel.background": "#1f1f1fff",
    "keybindingLabel.foreground": "#e1dfdfff",
    "keybindingLabel.border": "#3e3e3eff",
    "keybindingLabel.bottomBorder": "#3e3e3eff",
    "statusBar.foreground": "#b0afafff",
    "statusBar.background": "#292929ff",
    "statusBar.border": "#3e3e3eff",
    "statusBar.noFolderBackground": "#292929ff",
    "statusBar.debuggingBackground": "#891524ff",
    "statusBar.debuggingForeground": "#ffffffff",
    "statusBarItem.prominentBackground": "#282e34",
    "editorGroupHeader.tabsBackground": "#151515ff",
    "editorGroupHeader.tabsBorder": "#3e3e3eff",
    "editorGroup.border": "#3e3e3eff",
    "tab.activeForeground": "#e1dfdfff",
    "tab.inactiveForeground": "#b0afafff",
    "tab.inactiveBackground": "#151515ff",
    "tab.activeBackground": "#1f1f1fff",
    "tab.activeBorder": "#1f1f1fff",
    "tab.activeBorderTop": "#7895ffff",
    "tab.border": "#3e3e3eff",
    "tab.hoverBackground": "#1f1f1fff",
    "tab.unfocusedActiveForeground": "#828282ff",
    "tab.unfocusedInactiveForeground": "#828282ff",
    "tab.unfocusedHoverForeground": "#b0afafff",
    "tab.unfocusedHoverBackground": "#292929ff",
    "tab.unfocusedActiveBorderTop": "#3e3e3eff",
    "tab.unfocusedActiveBorder": "#1f1f1fff",
    "breadcrumb.foreground": "#999999ff",
    "breadcrumb.focusForeground": "#e1dfdfff",
    "breadcrumb.activeSelectionForeground": "#b0afafff",
    "breadcrumbPicker.background": "#1f1f1fff",
    "editor.foreground": "#e1dfdfff",
    "editor.background": "#121316ff",
    "editorLink.activeForeground": "#7895ffff",
    "editorCodeLens.foreground": "#999999ff",
    "editorWidget.background": "#292929ff",
    "editorWidget.border": "#6a6a6aff",
    "editor.foldBackground": "#252525ff",
    "editor.lineHighlightBackground": "#292929ff",
    "editorLineNumber.foreground": "#535353ff",
    "editorLineNumber.activeForeground": "#e1dfdfff",
    "editorIndentGuide.background": "#3e3e3eff",
    "editorIndentGuide.activeBackground": "#535353ff",
    "editorWhitespace.foreground": "#535353ff",
    "editorCursor.foreground": "#bbceffff",
    "editorError.foreground": "#fc8f8eff",
    "editorWarning.foreground": "#ffc26eff",
    "editorInfo.foreground": "#98b1ffff",
    "editorHint.foreground": "#66ce98ff",
    "editorLightBulb.foreground": "#ffc26eff",
    "problemsErrorIcon.foreground": "#f76769ff",
    "problemsWarningIcon.foreground": "#ffa23eff",
    "problemsInfoIcon.foreground": "#999999ff",
    "sash.hoverBorder": "#7895ffff",
    "editor.findMatchBackground": "#83431466",
    "editor.findMatchBorder": "#ffa23eff",
    "editor.findMatchHighlightBackground": "#83431499",
    "editor.findMatchHighlightBorder": "#834314ff",
    "peekView.border": "#7895ffff",
    "peekViewEditor.matchHighlightBackground": "#83431466",
    "peekViewEditor.matchHighlightBorder": "#ffa23e4d",
    "peekViewResult.matchHighlightBackground": "#83431466",
    "peekViewEditor.background": "#151515ff",
    "peekViewResult.background": "#0a0a0aff",
    "peekViewResult.selectionBackground": "#3e3e3eff",
    "editor.linkedEditingBackground": "#4d21bb99",
    "editor.inactiveSelectionBackground": "#3252b84d",
    "editor.selectionBackground": "#3252b880",
    "editor.selectionHighlightBackground": "#3e3e3e99",
    "editor.selectionHighlightBorder": "#3e3e3eff",
    "editor.wordHighlightBackground": "#882d0066",
    "editor.wordHighlightStrongBackground": "#882d0099",
    "editor.wordHighlightBorder": "#882d00ff",
    "editor.wordHighlightStrongBorder": "#882d00ff",
    "editorBracketMatch.background": "#004b5e99",
    "editorBracketMatch.border": "#004b5eff",
    "editorGutter.modifiedBackground": "#4563caff",
    "editorGutter.addedBackground": "#17975f80",
    "editorGutter.deletedBackground": "#df4047ff",
    "editorGutter.foldingControlForeground": "#999999ff",
    "diffEditor.border": "#3e3e3eff",
    "diffEditor.insertedTextBackground": "#17975f33",
    "diffEditor.removedTextBackground": "#df404733",
    "diffEditor.insertedLineBackground": "#17975f33",
    "diffEditor.removedLineBackground": "#df404733",
    "diffEditorGutter.insertedLineBackground": "#17975f1a",
    "diffEditorGutter.removedLineBackground": "#df40471a",
    "diffEditorOverview.insertedForeground": "#17975f66",
    "diffEditorOverview.removedForeground": "#df404766",
    "diffEditor.move.border": "#828282ff",
    "diffEditor.moveActive.border": "#7895ffff",
    "scrollbar.shadow": "#0008",
    "scrollbarSlider.background": "#6a737d33",
    "scrollbarSlider.hoverBackground": "#6a737d44",
    "scrollbarSlider.activeBackground": "#6a737d88",
    "editorOverviewRuler.border": "#000000ff",
    "panel.background": "#151515ff",
    "panel.border": "#3e3e3eff",
    "panelTitle.activeBorder": "#7895ffff",
    "panelTitle.activeForeground": "#e1dfdfff",
    "panelTitle.inactiveForeground": "#b0afafff",
    "panelInput.border": "#3e3e3eff",
    "panelSectionHeader.background": "#0000",
    "panelSectionHeader.foreground": "#e1dfdfff",
    "panelSection.border": "#3e3e3eff",
    "menu.foreground": "#e1dfdfff",
    "menu.background": "#151515ff",
    "menu.selectionForeground": "#e1dfdfff",
    "menu.selectionBackground": "#292929ff",
    "menu.separatorBackground": "#3e3e3eff",
    "menu.border": "#494949ff",
    "terminal.foreground": "#b0afafff",
    "terminal.tab.activeBorder": "#7895ffff",
    "terminalCursor.background": "#6a6a6aff",
    "terminalCursor.foreground": "#98b1ffff",
    "terminal.ansiBrightWhite": "#fdfcfcff",
    "terminal.ansiWhite": "#b0afafff",
    "terminal.ansiBrightBlack": "#999999ff",
    "terminal.ansiBlack": "#828282ff",
    "terminal.ansiBlue": "#7895ffff",
    "terminal.ansiBrightBlue": "#98b1ffff",
    "terminal.ansiGreen": "#17b877ff",
    "terminal.ansiBrightGreen": "#66ce98ff",
    "terminal.ansiCyan": "#25a6e9ff",
    "terminal.ansiBrightCyan": "#71c2eeff",
    "terminal.ansiRed": "#f76769ff",
    "terminal.ansiBrightRed": "#fc8f8eff",
    "terminal.ansiMagenta": "#a87ffbff",
    "terminal.ansiBrightMagenta": "#c8aaffff",
    "terminal.ansiYellow": "#ffa23eff",
    "terminal.ansiBrightYellow": "#ffc26eff",
    "gitDecoration.addedResourceForeground": "#17b877ff",
    "gitDecoration.untrackedResourceForeground": "#17b877ff",
    "gitDecoration.modifiedResourceForeground": "#7895ffff",
    "gitDecoration.deletedResourceForeground": "#f76769ff",
    "gitDecoration.conflictingResourceForeground": "#ffc26eff",
    "gitDecoration.ignoredResourceForeground": "#828282ff",
    "gitDecoration.submoduleResourceForeground": "#828282ff",
    "debugToolBar.background": "#292929ff",
    "editor.stackFrameHighlightBackground": "#C6902625",
    "editor.focusedStackFrameHighlightBackground": "#2b6a3033",
    "settings.headerForeground": "#e1dfdfff",
    "settings.modifiedItemIndicator": "#5876deff",
    "welcomePage.buttonBackground": "#3e3e3eff",
    "welcomePage.buttonHoverBackground": "#535353ff",
    "editorBracketHighlight.foreground1": "#85cdf1ff",
    "editorBracketHighlight.foreground2": "#ffd395ff",
    "editorBracketHighlight.foreground3": "#bd9cfeff",
    "editorBracketHighlight.foreground4": "#85cdf1ff",
    "editorBracketHighlight.foreground5": "#ffd395ff",
    "editorBracketHighlight.foreground6": "#bd9cfeff",
    "editorGhostText.foreground": "#6a6a6aff",
    "editorInlayHint.foreground": "#999999ff",
    "editorInlayHint.background": "#82828233",
    "editorInlayHint.typeForeground": "#999999ff",
    "editorInlayHint.typeBackground": "#82828233",
  },
  semanticHighlighting: true,
  semanticTokenColors: {
    "property.annotation": "#85cdf1ff",
    annotation: "#85cdf1ff",
    class: "#8da8ffff",
  },
  tokenColors: [
    {
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: {
        foreground: "#8e8e8eff",
      },
    },
    {
      scope: [
        "constant",
        "entity.name.constant",
        "variable.other.constant",
        "variable.language",
      ],
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: ["entity", "entity.name"],
      settings: {
        foreground: "#bd9cfeff",
      },
    },
    {
      scope: "variable.parameter.function",
      settings: {
        foreground: "#e1dfdfff",
      },
    },
    {
      scope: "entity.name.tag",
      settings: {
        foreground: "#77d5a3ff",
      },
    },
    {
      scope: "keyword",
      settings: {
        foreground: "#fd8da3ff",
      },
    },
    {
      scope: ["storage", "storage.type"],
      settings: {
        foreground: "#fd8da3ff",
      },
    },
    {
      scope: ["annotation"],
      settings: {
        foreground: "#fd8da3ff",
      },
    },
    {
      scope: [
        "storage.modifier.package",
        "storage.modifier.import",
        "storage.type.java",
      ],
      settings: {
        foreground: "#e1dfdfff",
      },
    },
    {
      scope: [
        "string",
        "punctuation.definition.string",
        "string punctuation.section.embedded source",
      ],
      settings: {
        foreground: "#77d5a3ff",
      },
    },
    {
      scope: [
        "string.quoted.double.html",
        "string.quoted.single.html",
        "string.unquoted.html",
        "punctuation.definition.string.begin.html",
        "punctuation.definition.string.end.html",
        "string.quoted.double.xml",
        "string.quoted.single.xml",
        "string.unquoted.xml",
        "punctuation.definition.string.begin.xml",
        "punctuation.definition.string.end.xml",
        "string punctuation.section.embedded source",
      ],
      settings: {
        foreground: "#85cdf1ff",
      },
    },
    {
      scope: "support",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: ["support.type.property-name", "entity.name.tag.yaml"],
      settings: {
        foreground: "#85cdf1ff",
      },
    },
    {
      scope: "meta.property-name",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: "variable",
      settings: {
        foreground: "#ffd395ff",
      },
    },
    {
      scope: "variable.other",
      settings: {
        foreground: "#e1dfdfff",
      },
    },
    {
      scope: "invalid.broken",
      settings: {
        fontStyle: "italic",
        foreground: "#ffc6d0ff",
      },
    },
    {
      scope: "invalid.deprecated",
      settings: {
        fontStyle: "italic",
        foreground: "#ffc6d0ff",
      },
    },
    {
      scope: "invalid.illegal",
      settings: {
        fontStyle: "italic",
        foreground: "#ffc6d0ff",
      },
    },
    {
      scope: "invalid.unimplemented",
      settings: {
        fontStyle: "italic",
        foreground: "#ffc6d0ff",
      },
    },
    {
      scope: "carriage-return",
      settings: {
        fontStyle: "italic underline",
        background: "#fd8da3ff",
        foreground: "#292929ff",
        content: "^M",
      },
    },
    {
      scope: "message.error",
      settings: {
        foreground: "#ffc6d0ff",
      },
    },
    {
      scope: "string source",
      settings: {
        foreground: "#e1dfdfff",
      },
    },
    {
      scope: "string variable",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: ["source.regexp", "string.regexp"],
      settings: {
        foreground: "#77d5a3ff",
      },
    },
    {
      scope: [
        "string.regexp.character-class",
        "string.regexp constant.character.escape",
        "string.regexp source.ruby.embedded",
        "string.regexp string.regexp.arbitrary-repitition",
      ],
      settings: {
        foreground: "#77d5a3ff",
      },
    },
    {
      scope: "string.regexp constant.character.escape",
      settings: {
        fontStyle: "bold",
        foreground: "#77d5a3ff",
      },
    },
    {
      scope: "support.constant",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: "support.variable",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: "meta.module-reference",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: "punctuation.definition.list.begin.markdown",
      settings: {
        foreground: "#ffd395ff",
      },
    },
    {
      scope: ["markup.heading", "markup.heading entity.name"],
      settings: {
        fontStyle: "bold",
        foreground: "#8da8ffff",
      },
    },
    {
      scope: "markup.quote",
      settings: {
        foreground: "#77d5a3ff",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        fontStyle: "italic",
        foreground: "#e1dfdfff",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        fontStyle: "bold",
        foreground: "#e1dfdfff",
      },
    },
    {
      scope: "markup.raw",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: [
        "markup.deleted",
        "meta.diff.header.from-file",
        "punctuation.definition.deleted",
      ],
      settings: {
        background: "#670023ff",
        foreground: "#ffc6d0ff",
      },
    },
    {
      scope: [
        "markup.inserted",
        "meta.diff.header.to-file",
        "punctuation.definition.inserted",
      ],
      settings: {
        background: "#00391fff",
        foreground: "#77d5a3ff",
      },
    },
    {
      scope: ["markup.changed", "punctuation.definition.changed"],
      settings: {
        background: "#834314ff",
        foreground: "#ffd395ff",
      },
    },
    {
      scope: ["markup.ignored", "markup.untracked"],
      settings: {
        foreground: "#3e3e3eff",
        background: "#8da8ffff",
      },
    },
    {
      scope: "meta.diff.range",
      settings: {
        foreground: "#bd9cfeff",
        fontStyle: "bold",
      },
    },
    {
      scope: "meta.diff.header",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: "meta.separator",
      settings: {
        fontStyle: "bold",
        foreground: "#8da8ffff",
      },
    },
    {
      scope: "meta.output",
      settings: {
        foreground: "#8da8ffff",
      },
    },
    {
      scope: [
        "brackethighlighter.tag",
        "brackethighlighter.curly",
        "brackethighlighter.round",
        "brackethighlighter.square",
        "brackethighlighter.angle",
        "brackethighlighter.quote",
      ],
      settings: {
        foreground: "#a8a8a8ff",
      },
    },
    {
      scope: "brackethighlighter.unmatched",
      settings: {
        foreground: "#ffc6d0ff",
      },
    },
    {
      scope: ["constant.other.reference.link", "string.other.link"],
      settings: {
        foreground: "#77d5a3ff",
        fontStyle: "underline",
      },
    },
  ],
};

export const GOOGLE_LIGHT_THEME = {
  name: "Google-Light",
  codeFontFamily: "0xProto",
  colors: {
    focusBorder: "#5876deff",
    foreground: "#292929ff",
    "icon.foreground": "#292929ff",
    "widget.shadow": "#29292940",
    descriptionForeground: "#6a6a6aff",
    errorForeground: "#c1313bff",
    "toolbar.hoverBackground": "#29292914",
    "toolbar.activeBackground": "#29292929",
    "textLink.foreground": "#4563caff",
    "textLink.activeForeground": "#183da4ff",
    "textBlockQuote.background": "#fdfcfcff",
    "textBlockQuote.border": "#e1dfdfff",
    "textCodeBlock.background": "#faf8f8ff",
    "textPreformat.foreground": "#6a6a6aff",
    "textSeparator.foreground": "#b0afafff",
    "list.warningForeground": "#c16f23ff",
    "list.errorForeground": "#c1313bff",
    "button.background": "#4563caff",
    "button.hoverBackground": "#3252b8ff",
    "button.foreground": "#ffffffff",
    "button.secondaryBackground": "#e1dfdfff",
    "button.secondaryForeground": "#000000ff",
    "button.secondaryHoverBackground": "#b0afafff",
    "checkbox.background": "#ffffffff",
    "checkbox.foreground": "#3e3e3eff",
    "checkbox.border": "#c8c7c7ff",
    "dropdown.background": "#ffffffff",
    "dropdown.border": "#c8c7c7ff",
    "dropdown.foreground": "#3e3e3eff",
    "dropdown.listBackground": "#faf8f8ff",
    "input.background": "#ffffffff",
    "input.border": "#c8c7c7ff",
    "input.foreground": "#3e3e3eff",
    "input.placeholderForeground": "#999999ff",
    "inputValidation.errorBorder": "#c1313bff",
    "inputOption.activeBorder": "#7895ffff",
    "inputOption.activeBackground": "#7895ff4d",
    "inputOption.activeForeground": "#292929ff",
    "badge.foreground": "#4563caff",
    "badge.background": "#dee7fcff",
    "progressBar.background": "#7895ffff",
    "titleBar.activeForeground": "#3e3e3eff",
    "titleBar.activeBackground": "#ffffffff",
    "titleBar.inactiveForeground": "#6a6a6aff",
    "titleBar.inactiveBackground": "#faf8f8ff",
    "titleBar.border": "#e1dfdfff",
    "commandCenter.background": "#ffffffff",
    "commandCenter.foreground": "#6a6a6aff",
    "commandCenter.border": "#e1dfdfff",
    "commandCenter.activeBackground": "#fdfcfcff",
    "commandCenter.activeForeground": "#3e3e3eff",
    "commandCenter.activeBorder": "#c8c7c7ff",
    "commandCenter.inactiveForeground": "#828282ff",
    "commandCenter.inactiveBorder": "#e1dfdfff",
    "activityBar.foreground": "#3e3e3eff",
    "activityBar.inactiveForeground": "#999999ff",
    "activityBar.background": "#ffffffff",
    "activityBarBadge.foreground": "#ffffffff",
    "activityBarBadge.background": "#4563caff",
    "activityBar.activeBorder": "#7895ffff",
    "activityBar.border": "#e1dfdfff",
    "sideBar.foreground": "#535353ff",
    "sideBar.background": "#faf8f8ff",
    "sideBar.border": "#e1dfdfff",
    "sideBarTitle.foreground": "#3e3e3eff",
    "sideBarSectionHeader.foreground": "#3e3e3eff",
    "sideBarSectionHeader.background": "#faf8f8ff",
    "sideBarSectionHeader.border": "#e1dfdfff",
    "list.hoverForeground": "#3e3e3eff",
    "list.inactiveSelectionForeground": "#3e3e3eff",
    "list.activeSelectionForeground": "#3e3e3eff",
    "list.inactiveSelectionBackground": "#eeececff",
    "list.hoverBackground": "#eeececff",
    "list.activeSelectionBackground": "#e1dfdfff",
    "list.inactiveFocusBackground": "#dee7fcff",
    "list.focusBackground": "#bbceffff",
    "tree.indentGuidesStroke": "#e1dfdfff",
    "notificationCenterHeader.foreground": "#6a6a6aff",
    "notificationCenterHeader.background": "#ffffffff",
    "notifications.foreground": "#3e3e3eff",
    "notifications.background": "#faf8f8ff",
    "notifications.border": "#c8c7c7ff",
    "notificationToast.border": "#c8c7c7ff",
    "notificationsErrorIcon.foreground": "#df4047ff",
    "notificationsWarningIcon.foreground": "#df8128ff",
    "notificationsInfoIcon.foreground": "#828282ff",
    "pickerGroup.border": "#e1dfdfff",
    "pickerGroup.foreground": "#3e3e3eff",
    "quickInput.background": "#ffffffff",
    "quickInput.foreground": "#3e3e3eff",
    "quickInputTitle.background": "#ffffffff",
    "keybindingLabel.background": "#faf8f8ff",
    "keybindingLabel.foreground": "#3e3e3eff",
    "keybindingLabel.border": "#e1dfdfff",
    "keybindingLabel.bottomBorder": "#e1dfdfff",
    "statusBar.foreground": "#6a6a6aff",
    "statusBar.background": "#ffffffff",
    "statusBar.border": "#e1dfdfff",
    "statusBar.noFolderBackground": "#ffffffff",
    "statusBar.debuggingBackground": "#fc8f8eff",
    "statusBar.debuggingForeground": "#000000ff",
    "statusBarItem.prominentBackground": "#e8eaed",
    "editorGroupHeader.tabsBackground": "#faf8f8ff",
    "editorGroupHeader.tabsBorder": "#e1dfdfff",
    "editorGroup.border": "#e1dfdfff",
    "tab.activeForeground": "#3e3e3eff",
    "tab.inactiveForeground": "#6a6a6aff",
    "tab.inactiveBackground": "#faf8f8ff",
    "tab.activeBackground": "#ffffffff",
    "tab.activeBorder": "#ffffffff",
    "tab.activeBorderTop": "#5876deff",
    "tab.border": "#e1dfdfff",
    "tab.hoverBackground": "#ffffffff",
    "tab.unfocusedActiveForeground": "#b0afafff",
    "tab.unfocusedInactiveForeground": "#b0afafff",
    "tab.unfocusedHoverForeground": "#6a6a6aff",
    "tab.unfocusedHoverBackground": "#ffffffff",
    "tab.unfocusedActiveBorderTop": "#e1dfdfff",
    "tab.unfocusedActiveBorder": "#ffffffff",
    "breadcrumb.foreground": "#828282ff",
    "breadcrumb.focusForeground": "#3e3e3eff",
    "breadcrumb.activeSelectionForeground": "#6a6a6aff",
    "breadcrumbPicker.background": "#fdfcfcff",
    "editor.foreground": "#292929ff",
    "editor.background": "#ffffffff",
    "editorLink.activeForeground": "#4563caff",
    "editorCodeLens.foreground": "#6a6a6aff",
    "editorWidget.background": "#ffffffff",
    "editorWidget.border": "#b0afafff",
    "editor.foldBackground": "#faf8f8ff",
    "editor.lineHighlightBackground": "#faf8f8ff",
    "editorLineNumber.foreground": "#c8c7c7ff",
    "editorLineNumber.activeForeground": "#292929ff",
    "editorIndentGuide.background": "#eeececff",
    "editorIndentGuide.activeBackground": "#c8c7c7ff",
    "editorWhitespace.foreground": "#c8c7c7ff",
    "editorCursor.foreground": "#3252b8ff",
    "editorError.foreground": "#df4047ff",
    "editorWarning.foreground": "#df8128ff",
    "editorInfo.foreground": "#5876deff",
    "editorHint.foreground": "#17975fff",
    "editorLightBulb.foreground": "#df8128ff",
    "problemsErrorIcon.foreground": "#df4047ff",
    "problemsWarningIcon.foreground": "#df8128ff",
    "problemsInfoIcon.foreground": "#828282ff",
    "sash.hoverBorder": "#5876deff",
    "editor.findMatchBackground": "#df812866",
    "editor.findMatchBorder": "#df8128ff",
    "editor.findMatchHighlightBackground": "#ffc26e66",
    "editor.findMatchHighlightBorder": "#ffc26eff",
    "peekView.border": "#5876deff",
    "peekViewEditor.matchHighlightBackground": "#df812866",
    "peekViewEditor.matchHighlightBorder": "#df8128ff",
    "peekViewResult.matchHighlightBackground": "#df812866",
    "peekViewEditor.background": "#faf8f8ff",
    "peekViewResult.background": "#eeececff",
    "peekViewResult.selectionBackground": "#e1dfdfff",
    "editor.linkedEditingBackground": "#a87ffb99",
    "editor.inactiveSelectionBackground": "#bbceff66",
    "editor.selectionBackground": "#bbceff99",
    "editor.selectionHighlightBackground": "#98e4b999",
    "editor.selectionHighlightBorder": "#98e4b999",
    "editor.wordHighlightBackground": "#ffc9aa66",
    "editor.wordHighlightStrongBackground": "#ffc9aa66",
    "editor.wordHighlightBorder": "#ffc9aaff",
    "editor.wordHighlightStrongBorder": "#ffc9aaff",
    "editorBracketMatch.background": "#abe1f899",
    "editorBracketMatch.border": "#abe1f8ff",
    "editorGutter.modifiedBackground": "#98b1ffff",
    "editorGutter.addedBackground": "#98e4b9ff",
    "editorGutter.deletedBackground": "#fc8f8eff",
    "editorGutter.foldingControlForeground": "#6a6a6aff",
    "diffEditor.border": "#e1dfdfff",
    "diffEditor.insertedTextBackground": "#17b87733",
    "diffEditor.removedTextBackground": "#f7676933",
    "diffEditor.insertedLineBackground": "#66ce9833",
    "diffEditor.removedLineBackground": "#fc8f8e33",
    "diffEditorGutter.insertedLineBackground": "#66ce981a",
    "diffEditorGutter.removedLineBackground": "#fc8f8e1a",
    "diffEditorOverview.insertedForeground": "#66ce9866",
    "diffEditorOverview.removedForeground": "#fc8f8e66",
    "diffEditor.move.border": "#999999ff",
    "diffEditor.moveActive.border": "#4563caff",
    "scrollbar.shadow": "#6a737d33",
    "scrollbarSlider.background": "#959da533",
    "scrollbarSlider.hoverBackground": "#959da544",
    "scrollbarSlider.activeBackground": "#959da588",
    "editorOverviewRuler.border": "#ffffffff",
    "panel.background": "#faf8f8ff",
    "panel.border": "#e1dfdfff",
    "panelTitle.activeBorder": "#5876deff",
    "panelTitle.activeForeground": "#3e3e3eff",
    "panelTitle.inactiveForeground": "#6a6a6aff",
    "panelInput.border": "#e1dfdfff",
    "panelSectionHeader.background": "#0000",
    "panelSectionHeader.foreground": "#3e3e3eff",
    "panelSection.border": "#e1dfdfff",
    "menu.foreground": "#3e3e3eff",
    "menu.background": "#faf8f8ff",
    "menu.selectionForeground": "#3e3e3eff",
    "menu.selectionBackground": "#e1dfdfff",
    "menu.separatorBackground": "#e1dfdfff",
    "menu.border": "#c8c7c7ff",
    "terminal.foreground": "#535353ff",
    "terminal.tab.activeBorder": "#5876deff",
    "terminalCursor.background": "#b0afafff",
    "terminalCursor.foreground": "#4563caff",
    "terminal.ansiBrightWhite": "#535353ff",
    "terminal.ansiWhite": "#6a6a6aff",
    "terminal.ansiBrightBlack": "#000000ff",
    "terminal.ansiBlack": "#3e3e3eff",
    "terminal.ansiBlue": "#4563caff",
    "terminal.ansiBrightBlue": "#002583ff",
    "terminal.ansiGreen": "#007b49ff",
    "terminal.ansiBrightGreen": "#00522fff",
    "terminal.ansiCyan": "#0075a2ff",
    "terminal.ansiBrightCyan": "#00607eff",
    "terminal.ansiRed": "#d03941ff",
    "terminal.ansiBrightRed": "#a52430ff",
    "terminal.ansiMagenta": "#6f4cdeff",
    "terminal.ansiBrightMagenta": "#4d21bbff",
    "terminal.ansiYellow": "#a65921ff",
    "terminal.ansiBrightYellow": "#904b1aff",
    "gitDecoration.addedResourceForeground": "#17975fff",
    "gitDecoration.untrackedResourceForeground": "#17975fff",
    "gitDecoration.modifiedResourceForeground": "#5876deff",
    "gitDecoration.deletedResourceForeground": "#df4047ff",
    "gitDecoration.conflictingResourceForeground": "#c16f23ff",
    "gitDecoration.ignoredResourceForeground": "#999999ff",
    "gitDecoration.submoduleResourceForeground": "#999999ff",
    "debugToolBar.background": "#ffffffff",
    "editor.stackFrameHighlightBackground": "#ffd33d33",
    "editor.focusedStackFrameHighlightBackground": "#28a74525",
    "settings.headerForeground": "#3e3e3eff",
    "settings.modifiedItemIndicator": "#7895ffff",
    "welcomePage.buttonBackground": "#faf8f8ff",
    "welcomePage.buttonHoverBackground": "#e1dfdfff",
    "editorBracketHighlight.foreground1": "#0075a2ff",
    "editorBracketHighlight.foreground2": "#d07826ff",
    "editorBracketHighlight.foreground3": "#6f4cdeff",
    "editorBracketHighlight.foreground4": "#0075a2ff",
    "editorBracketHighlight.foreground5": "#d07826ff",
    "editorBracketHighlight.foreground6": "#6f4cdeff",
    "editorGhostText.foreground": "#b0afafff",
    "editorInlayHint.foreground": "#828282ff",
    "editorInlayHint.background": "#8282821a",
    "editorInlayHint.typeForeground": "#828282ff",
    "editorInlayHint.typeBackground": "#8282821a",
  },
  semanticHighlighting: true,
  semanticTokenColors: {
    "property.annotation": "#0075a2ff",
    annotation: "#0075a2ff",
    class: "#3252b8ff",
  },
  tokenColors: [
    {
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: {
        foreground: "#707070ff",
      },
    },
    {
      scope: [
        "constant",
        "entity.name.constant",
        "variable.other.constant",
        "variable.language",
      ],
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: ["entity", "entity.name"],
      settings: {
        foreground: "#6f4cdeff",
      },
    },
    {
      scope: "variable.parameter.function",
      settings: {
        foreground: "#292929ff",
      },
    },
    {
      scope: "entity.name.tag",
      settings: {
        foreground: "#007b49ff",
      },
    },
    {
      scope: "keyword",
      settings: {
        foreground: "#c43058ff",
      },
    },
    {
      scope: ["storage", "storage.type"],
      settings: {
        foreground: "#c43058ff",
      },
    },
    {
      scope: ["annotation"],
      settings: {
        foreground: "#c43058ff",
      },
    },
    {
      scope: [
        "storage.modifier.package",
        "storage.modifier.import",
        "storage.type.java",
      ],
      settings: {
        foreground: "#292929ff",
      },
    },
    {
      scope: [
        "string",
        "punctuation.definition.string",
        "string punctuation.section.embedded source",
      ],
      settings: {
        foreground: "#007b49ff",
      },
    },
    {
      scope: [
        "string.quoted.double.html",
        "string.quoted.single.html",
        "string.unquoted.html",
        "punctuation.definition.string.begin.html",
        "punctuation.definition.string.end.html",
        "string.quoted.double.xml",
        "string.quoted.single.xml",
        "string.unquoted.xml",
        "punctuation.definition.string.begin.xml",
        "punctuation.definition.string.end.xml",
        "string punctuation.section.embedded source",
      ],
      settings: {
        foreground: "#0075a2ff",
      },
    },
    {
      scope: "support",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: ["support.type.property-name", "entity.name.tag.yaml"],
      settings: {
        foreground: "#0075a2ff",
      },
    },
    {
      scope: "meta.property-name",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: "variable",
      settings: {
        foreground: "#d07826ff",
      },
    },
    {
      scope: "variable.other",
      settings: {
        foreground: "#292929ff",
      },
    },
    {
      scope: "invalid.broken",
      settings: {
        fontStyle: "italic",
        foreground: "#ad1c48ff",
      },
    },
    {
      scope: "invalid.deprecated",
      settings: {
        fontStyle: "italic",
        foreground: "#ad1c48ff",
      },
    },
    {
      scope: "invalid.illegal",
      settings: {
        fontStyle: "italic",
        foreground: "#ad1c48ff",
      },
    },
    {
      scope: "invalid.unimplemented",
      settings: {
        fontStyle: "italic",
        foreground: "#ad1c48ff",
      },
    },
    {
      scope: "carriage-return",
      settings: {
        fontStyle: "italic underline",
        background: "#c43058ff",
        foreground: "#fdfcfcff",
        content: "^M",
      },
    },
    {
      scope: "message.error",
      settings: {
        foreground: "#ad1c48ff",
      },
    },
    {
      scope: "string source",
      settings: {
        foreground: "#292929ff",
      },
    },
    {
      scope: "string variable",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: ["source.regexp", "string.regexp"],
      settings: {
        foreground: "#007b49ff",
      },
    },
    {
      scope: [
        "string.regexp.character-class",
        "string.regexp constant.character.escape",
        "string.regexp source.ruby.embedded",
        "string.regexp string.regexp.arbitrary-repitition",
      ],
      settings: {
        foreground: "#007b49ff",
      },
    },
    {
      scope: "string.regexp constant.character.escape",
      settings: {
        fontStyle: "bold",
        foreground: "#007b49ff",
      },
    },
    {
      scope: "support.constant",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: "support.variable",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: "meta.module-reference",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: "punctuation.definition.list.begin.markdown",
      settings: {
        foreground: "#d07826ff",
      },
    },
    {
      scope: ["markup.heading", "markup.heading entity.name"],
      settings: {
        fontStyle: "bold",
        foreground: "#3252b8ff",
      },
    },
    {
      scope: "markup.quote",
      settings: {
        foreground: "#007b49ff",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        fontStyle: "italic",
        foreground: "#292929ff",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        fontStyle: "bold",
        foreground: "#292929ff",
      },
    },
    {
      scope: "markup.raw",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: [
        "markup.deleted",
        "meta.diff.header.from-file",
        "punctuation.definition.deleted",
      ],
      settings: {
        background: "#fff4f5ff",
        foreground: "#ad1c48ff",
      },
    },
    {
      scope: [
        "markup.inserted",
        "meta.diff.header.to-file",
        "punctuation.definition.inserted",
      ],
      settings: {
        background: "#e8fbecff",
        foreground: "#007b49ff",
      },
    },
    {
      scope: ["markup.changed", "punctuation.definition.changed"],
      settings: {
        background: "#fff0caff",
        foreground: "#d07826ff",
      },
    },
    {
      scope: ["markup.ignored", "markup.untracked"],
      settings: {
        foreground: "#faf8f8ff",
        background: "#3252b8ff",
      },
    },
    {
      scope: "meta.diff.range",
      settings: {
        foreground: "#6f4cdeff",
        fontStyle: "bold",
      },
    },
    {
      scope: "meta.diff.header",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: "meta.separator",
      settings: {
        fontStyle: "bold",
        foreground: "#3252b8ff",
      },
    },
    {
      scope: "meta.output",
      settings: {
        foreground: "#3252b8ff",
      },
    },
    {
      scope: [
        "brackethighlighter.tag",
        "brackethighlighter.curly",
        "brackethighlighter.round",
        "brackethighlighter.square",
        "brackethighlighter.angle",
        "brackethighlighter.quote",
      ],
      settings: {
        foreground: "#6a6a6aff",
      },
    },
    {
      scope: "brackethighlighter.unmatched",
      settings: {
        foreground: "#ad1c48ff",
      },
    },
    {
      scope: ["constant.other.reference.link", "string.other.link"],
      settings: {
        foreground: "#007b49ff",
        fontStyle: "underline",
      },
    },
  ],
};
